# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\BTA lc\PRO\mover ventana\vn_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(333, 151)
        self.bt_no = QtWidgets.QPushButton(Form)
        self.bt_no.setGeometry(QtCore.QRect(10, 10, 40, 30))
        self.bt_no.setMinimumSize(QtCore.QSize(40, 30))
        self.bt_no.setMaximumSize(QtCore.QSize(40, 30))
        self.bt_no.setObjectName("bt_no")
        self.bt_ne = QtWidgets.QPushButton(Form)
        self.bt_ne.setGeometry(QtCore.QRect(280, 10, 40, 30))
        self.bt_ne.setMinimumSize(QtCore.QSize(40, 30))
        self.bt_ne.setMaximumSize(QtCore.QSize(40, 30))
        self.bt_ne.setObjectName("bt_ne")
        self.bt_so = QtWidgets.QPushButton(Form)
        self.bt_so.setGeometry(QtCore.QRect(10, 110, 40, 30))
        self.bt_so.setMinimumSize(QtCore.QSize(40, 30))
        self.bt_so.setMaximumSize(QtCore.QSize(40, 30))
        self.bt_so.setObjectName("bt_so")
        self.bt_se = QtWidgets.QPushButton(Form)
        self.bt_se.setGeometry(QtCore.QRect(280, 110, 40, 30))
        self.bt_se.setMinimumSize(QtCore.QSize(40, 30))
        self.bt_se.setMaximumSize(QtCore.QSize(40, 30))
        self.bt_se.setObjectName("bt_se")
        self.bt_ctop = QtWidgets.QPushButton(Form)
        self.bt_ctop.setGeometry(QtCore.QRect(110, 10, 111, 23))
        self.bt_ctop.setObjectName("bt_ctop")
        self.bt_cbot = QtWidgets.QPushButton(Form)
        self.bt_cbot.setGeometry(QtCore.QRect(110, 120, 111, 23))
        self.bt_cbot.setObjectName("bt_cbot")
        self.bt_c = QtWidgets.QPushButton(Form)
        self.bt_c.setGeometry(QtCore.QRect(130, 60, 71, 31))
        self.bt_c.setObjectName("bt_c")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_no.setText(_translate("Form", "NO"))
        self.bt_ne.setText(_translate("Form", "NE"))
        self.bt_so.setText(_translate("Form", "SO"))
        self.bt_se.setText(_translate("Form", "SE"))
        self.bt_ctop.setText(_translate("Form", "ARRIBA CENTRAR"))
        self.bt_cbot.setText(_translate("Form", "ABAJO CENTRAR"))
        self.bt_c.setText(_translate("Form", "CENTRAR"))
